### ISSUE TITLE
Opposed to enforcing raster handling?

### ISSUE THREAD

**Issue by mikejohnson51** [dblodgett-usgs/hyRefactor#20]
Hi @dblodgett-usgs,

Are you opposed to enforcing the transformation and precision setting catchments and raster grids within `reconcile_catchment_divides`?

Essentially place: 

```r
catchments <-  st_transform(catchments, st_crs(fdr)) 
st_precision(catchments) <- raster::res(fdr)[1]
```
Within the function?

Mike

**Comment by dblodgett-usgs** [comment]
No -- sounds fine. -- I wouldn't mind adding this functionality to st_compatiblize over in nhdplusTools too if you want?

**Comment by mikejohnson51** [comment]
I believe this is handled in PR #30
